const toast = document.getElementById('toast');
const dashboard = document.getElementById('dashboard-page');
const dynamic = document.getElementById('dynamic-page');
const modal = document.getElementById('learning-modal');
const currentUser = JSON.parse(localStorage.getItem('capacityConnectUser') || '{}');
document.getElementById('user-name').textContent = currentUser.name || 'Learner';
document.getElementById('user-role').textContent = currentUser.role || 'Learner';
document.getElementById('user-initials').textContent = (currentUser.name || 'Learner').split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase();
if (currentUser.role === 'Admin') document.querySelector('.admin-only').classList.add('visible-admin');
let toastTimer;
const course = (name, category, progress, icon) => `<article class="learning-item"><div class="mini-art">${icon}</div><div><span class="tag tag-blue">${category}</span><h3>${name}</h3><p>Module in progress · ${progress}% complete</p><div class="progress-line"><span style="width:${progress}%"></span></div></div><button class="continue-button open-lesson">Continue →</button></article>`;
const views = {
  'My Learning': `<section class="page-hero"><p class="eyebrow">LEARNING LIBRARY</p><h1>My learning</h1><p>Build skills at your own pace and keep your development moving.</p></section><div class="tab-row"><button class="active">In progress <b>5</b></button><button>Completed <b>12</b></button><button>Saved</button></div><div class="learning-list">${course('Cyber Security Awareness','MANDATORY TRAINING',65,'⌘')}${course('Leading with Purpose','LEADERSHIP',30,'♙')}${course('Strategic Communication','SOFT SKILLS',15,'◌')}</div>`,
  'Competencies': `<section class="page-hero"><p class="eyebrow">SKILL DEVELOPMENT</p><h1>My competencies</h1><p>See where you excel and where your next opportunity lies.</p></section><div class="competency-hero"><div class="big-donut"><strong>72%</strong><span>overall score</span></div><div><p class="eyebrow">YOUR CURRENT CAPACITY</p><h2>Strong foundation, ready to lead</h2><p>You're ahead of 68% of your learning group.</p></div></div><section class="skill-bars"><h2>Competency breakdown</h2>${[['Cyber Security',82],['Strategic Communication',68],['Team Collaboration',65],['Leadership',54]].map(x=>`<article><div><span>${x[0]}</span><b>${x[1]}%</b></div><i><u style="width:${x[1]}%"></u></i></article>`).join('')}</section>`,
  'Knowledge Hub': `<section class="page-hero"><p class="eyebrow">LEARN. SHARE. GROW.</p><h1>Knowledge hub</h1><p>Trusted resources, practical guides, and ideas from your organization.</p></section><section class="hub-feature"><div><span class="tag tag-blue">FEATURED PLAYBOOK</span><h2>Building resilient teams</h2><p>A practical guide to supporting teams through change, uncertainty, and growth.</p><button class="continue-button">Read playbook →</button></div><div class="hub-graphic">IDEAS<br>INTO<br>IMPACT</div></section><div class="resource-grid">${[['▤','Guides & playbooks'],['◉','Learning bites'],['♧','Community stories']].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>Explore practical knowledge for better work.</p><button>Explore →</button></article>`).join('')}</div>`,
  'Reports': `<section class="page-hero"><p class="eyebrow">LEARNING ANALYTICS</p><h1>Progress report</h1><p>A clear view of your learning impact this quarter.</p></section><div class="report-cards"><article><span>COURSES COMPLETED</span><strong>12</strong><small>↑ 33% vs. last quarter</small></article><article><span>LEARNING TIME</span><strong>28.5h</strong><small>↑ 8.5 hours this month</small></article><article><span>AVERAGE QUIZ SCORE</span><strong>86%</strong><small>↑ 6 points this quarter</small></article></div><section class="report-chart"><p class="eyebrow">MONTHLY LEARNING TIME</p><h2>Steady progress, meaningful gains</h2><div class="wide-bars">${[38,54,46,80,66,92].map((h,i)=>`<div><i style="height:${h}%"></i><span>${['Mar','Apr','May','Jun','Jul','Aug'][i]}</span></div>`).join('')}</div></section>`,
  'Settings': `<section class="page-hero"><p class="eyebrow">PERSONALIZATION</p><h1>Settings</h1><p>Manage your profile and learning experience.</p></section><section class="settings-panel"><div class="profile-row"><div class="avatar profile-avatar">AM</div><div><h2>Anirban Maity</h2><p>anirban@capacityconnect.org</p></div><button class="outline-button">Edit profile</button></div><div class="setting-line"><div><h3>Learning reminders</h3><p>Receive a gentle nudge to continue learning.</p></div><button class="toggle active-toggle"></button></div><div class="setting-line"><div><h3>Weekly learning summary</h3><p>Receive a weekly overview of your progress.</p></div><button class="toggle active-toggle"></button></div></section>`,
  'Explore': `<section class="page-hero"><p class="eyebrow">PERSONALIZED CATALOG</p><h1>Explore learning</h1><p>Choose a learning path that supports your next goal.</p></section><div class="catalog-grid">${[['⌘','Advanced Cyber Security','Protect your organization at every level.'],['♙','Effective Leadership','Lead teams with clarity and confidence.'],['↗','Managing Change','Turn change into opportunity.']].map(x=>`<article><div class="catalog-art">${x[0]}</div><div><span class="tag tag-blue">DEVELOPMENT</span><h3>${x[1]}</h3><p>${x[2]}</p><button class="continue-button">View course →</button></div></article>`).join('')}</div>`,
  'Certificates': `<section class="page-hero"><p class="eyebrow">RECOGNITION</p><h1>My certificates</h1><p>Celebrate the learning milestones you have achieved.</p></section><section class="certificate-card"><div class="certificate-seal">✦</div><div><span class="tag tag-blue">CERTIFICATE OF COMPLETION</span><h2>Cyber Security Foundations</h2><p>Awarded to ${currentUser.name || 'Learner'} · 20 August 2026</p></div><button class="continue-button download-certificate">Download PDF ↓</button></section><section class="quiz-card"><p class="eyebrow">READY FOR YOUR NEXT MILESTONE?</p><h2>Cyber Security Awareness quiz</h2><p>Pass this short assessment to earn your next certificate.</p><button class="continue-button open-quiz">Start quiz →</button></section>`,
  'Admin': `<section class="page-hero"><p class="eyebrow">ADMINISTRATOR WORKSPACE</p><h1>Learning management</h1><p>Manage course content and monitor organizational learning.</p></section><div class="admin-stats"><article><strong>148</strong><span>Active learners</span></article><article><strong>24</strong><span>Published courses</span></article><article><strong>86%</strong><span>Completion rate</span></article></div><section class="admin-panel"><div><h2>Course management</h2><p>Create a training program for your learners.</p></div><button class="continue-button add-course">+ Add a course</button></section><section class="admin-list"><p><b>Cyber Security Awareness</b><span>128 enrolled · Published</span><button>Manage</button></p><p><b>Leading with Purpose</b><span>94 enrolled · Published</span><button>Manage</button></p></section>`
};
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
function openLesson(){modal.classList.add('show-modal');modal.setAttribute('aria-hidden','false')}
function bindDynamic(){dynamic.querySelectorAll('.open-lesson').forEach(x=>x.addEventListener('click',openLesson));dynamic.querySelectorAll('.toggle').forEach(x=>x.addEventListener('click',()=>x.classList.toggle('active-toggle')));dynamic.querySelectorAll('.tab-row button').forEach(x=>x.addEventListener('click',()=>{x.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));x.classList.add('active')}));dynamic.querySelectorAll('.download-certificate').forEach(x=>x.addEventListener('click',()=>showToast('Certificate download is ready.')));dynamic.querySelectorAll('.add-course').forEach(x=>x.addEventListener('click',()=>showToast('New course draft created.')));dynamic.querySelectorAll('.open-quiz').forEach(x=>x.addEventListener('click',openQuiz))}
function openPage(page){document.getElementById('page-title').textContent=page;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));dashboard.classList.toggle('active-page',!views[page]);dynamic.classList.toggle('active-page',Boolean(views[page]));if(views[page])dynamic.innerHTML=views[page];document.querySelector('.sidebar').classList.remove('open');bindDynamic()}
document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>openPage(x.dataset.page)));
function openQuiz(){dynamic.innerHTML=`<section class="page-hero"><p class="eyebrow">ASSESSMENT</p><h1>Cyber Security Awareness quiz</h1><p>Question 1 of 3 · Choose the best answer.</p></section><section class="quiz-screen"><span class="quiz-counter">QUESTION 01</span><h2>What is a common sign of a phishing email?</h2><label><input type="radio" name="quiz" value="0" /> An email from a colleague you know</label><label><input type="radio" name="quiz" value="1" /> An urgent request for sensitive information</label><label><input type="radio" name="quiz" value="0" /> A routine calendar invitation</label><button class="continue-button submit-quiz">Submit answer →</button></section>`;dynamic.querySelector('.submit-quiz').addEventListener('click',()=>{const answer=dynamic.querySelector('input:checked');if(!answer){showToast('Please select an answer first.');return}localStorage.setItem('capacityConnectQuizScore',answer.value==='1'?'100':'67');openPage('Certificates');showToast(answer.value==='1'?'Excellent! You passed the quiz.':'Quiz completed — review the learning module.')})}
document.getElementById('continue-button').addEventListener('click',openLesson);document.getElementById('report-button').addEventListener('click',()=>openPage('Reports'));document.getElementById('notification-button').addEventListener('click',()=>showToast('You have 2 new learning reminders.'));document.querySelectorAll('.round-arrow').forEach(x=>x.addEventListener('click',()=>openPage('Explore')));document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('.modal-close').addEventListener('click',()=>modal.classList.remove('show-modal'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show-modal')});document.querySelector('.modal-continue').addEventListener('click',()=>{modal.classList.remove('show-modal');showToast('Great work! Lesson completed.')});document.getElementById('course-search').addEventListener('keydown',e=>{if(e.key==='Enter')openPage('Explore')});document.getElementById('sign-out').addEventListener('click',()=>{localStorage.removeItem('capacityConnectUser');window.location.replace('login.html')});
